coverage:
  ignore:
    - Parse/Tests/.*
    - ParseTwitterUtils/Tests/.*
    - ParseFacebookUtils/Tests/.*
  status:
    patch: true
    changes: true
    project:
      default:
        target: 65
comment: false
