language: objective-c
os: osx
osx_image: xcode11.2
branches:
  only:
    - master
    - /^v?[0-9]+\.[0-9]+\.[0-9]+(-.*)?$/
cache:
  - cocoapods
git:
  submodules: false

before_install:
  - git submodule update --init --recursive

jobs:
  include:
    - stage: release
      if: branch = master and tag IS present
      env: Deployment
      install: bundle install
      script:
      - ./Scripts/jazzy.sh
      - bundle exec rake package:release
      deploy:
        - provider: releases
          token:
            secure: $GITHUB_TOKEN # Set in travis-ci.org dashboard
          file_glob: true
          file: build/release/*
          cleanup: false
          on:
            tags: true
            all_branches: true
        - provider: pages
          cleanup: false
          token:
            secure: $GITHUB_TOKEN # Set in travis-ci.org dashboard
          local_dir: docs/
          on:
            all_branches: true
            tags: true
    - stage: release
      env: Cocoapods
      install:
        - bundle install
        - bundle exec pod setup
        - bundle exec pod repo update
      script: bundle exec pod trunk push Parse.podspec --allow-warnings
      deploy:
        provider: script
        skip_cleanup: true
        script: bundle exec pod trunk push Parse.podspec --allow-warnings
        on:
          tags: true
          all_branches: true
