language: objective-c
os: osx
osx_image: xcode8.3
branches:
  only:
    - master
    - /^v?[0-9]+.[0-9]+.[0-9]+(-.*)?$/
git:
  submodules: false

before_install:
  - git submodule update --init --recursive

stage: test
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
  - TEST_TYPE=iOS
  - TEST_TYPE=macOS
install: bundle install
script:
- |
  RAKE_TASK_NAME=$(echo "$TEST_TYPE" | tr '[:upper:]' '[:lower:]')
  bundle exec rake test:$RAKE_TASK_NAME
after_success:  bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: release
      env: Deployment
      install: bundle install
      script: bundle exec rake test:deployment
    - stage: release
      env: Cocoapods
      install: bundle install
      script: bundle exec rake test:cocoapods
    - stage: release
      env: Carthage
      install:
      - bundle install
      - brew update
      - brew install carthage || brew upgrade carthage
      script: bundle exec rake test:carthage